version: 2
jobs:
  build:
    working_directory: ~/python-examples
    docker:
      - image: circleci/python:3.7 # every job must define an image for the docker executor and subsequent jobs may define a different image.
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout  # checkout source code to working directory
      - run:
          command: |  # use pipenv to install dependencies
            sudo pip install pipenv
            mkdir reports
            pipenv install
            pipenv run py.test --junitxml=reports/pytest/pytest-report.xml
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"
      - store_test_results:
          path: reports




